name: 'LLM Release Action'
description: 'Analyze commits, suggest semantic version bumps, and generate multi-audience changelogs using LLM via LiteLLM.'
author: 'Joe Nosov'

branding:
  icon: 'git-commit'
  color: 'purple'

inputs:
  model:
    description: 'Default LiteLLM model string (e.g., anthropic/claude-3-haiku-20240307)'
    required: true
  model_analysis:
    description: 'Optional model for Phase 1 semantic analysis. Falls back to model if not set.'
    required: false
    default: ''
  model_changelog:
    description: 'Optional model for Phase 2 changelog generation. Falls back to model if not set.'
    required: false
    default: ''
  current_version:
    description: 'Current version to compare from. Auto-detects from latest semver tag if not provided.'
    required: false
  head_ref:
    description: 'Head ref to compare to'
    required: false
    default: 'HEAD'
  include_diffs:
    description: 'File patterns to include in diff analysis (comma-separated)'
    required: false
    default: '**/openapi*.yaml,**/migrations/**,**/*.proto'
  max_commits:
    description: 'Maximum recent commits to include in full'
    required: false
    default: '50'
  temperature:
    description: 'LLM temperature (0.0-2.0)'
    required: false
    default: '0.2'
  max_tokens:
    description: 'Maximum tokens in LLM response'
    required: false
    default: '4000'
  timeout:
    description: 'Request timeout in seconds'
    required: false
    default: '120'
  debug:
    description: 'Enable verbose debug logging'
    required: false
    default: 'false'
  dry_run:
    description: 'Perform analysis without suggesting version'
    required: false
    default: 'false'
  content_override:
    description: 'Markdown content for multi-repo analysis (bypasses git). Format: ## Repo\n### Features\n- item. See README.'
    required: false
    default: ''
  changelog_config:
    description: 'YAML config for audiences. Format: {audience: {preset, languages, tone, ...}}. Presets: developer, customer, executive, marketing, security, ops. See README.'
    required: false
    default: ''
  validate_injections:
    description: 'Prompt injection validation mode. "pattern" = regex only (default), "both" = pattern + LLM, "llm" = LLM only, "none" = disabled'
    required: false
    default: 'pattern'
  validation_model:
    description: 'Optional model for injection validation LLM checks. Falls back to model if not set.'
    required: false
    default: ''
  context_files:
    description: 'Comma-separated file patterns for project context (gitignore-style, supports negation). Examples: "README.md", "README.md,docs/API.md", "**/README.md,!**/node_modules/**"'
    required: false
    default: ''
  context_max_tokens:
    description: 'Maximum tokens for context content (increase for large-context models like Claude or GPT-4)'
    required: false
    default: '800'
  analyze_diffs:
    description: 'Enable diff analysis step to extract structured changes from file diffs'
    required: false
    default: 'false'
  diff_exclude_patterns:
    description: 'Comma-separated gitignore-style patterns for files to exclude from diff analysis'
    required: false
    default: '**/*.lock,**/package-lock.json,**/yarn.lock,**/Cargo.lock,**/poetry.lock,**/vendor/**,**/node_modules/**,**/*.generated.*,**/generated/**,**/*.min.js,**/*.min.css'
  diff_max_files:
    description: 'Maximum number of files to include in diff analysis'
    required: false
    default: '50'
  diff_max_total_lines:
    description: 'Maximum total lines of diff content to analyze'
    required: false
    default: '5000'

outputs:
  bump:
    description: 'Bump type (major, minor, patch)'
    value: ${{ steps.analyze.outputs.bump }}
  current_version:
    description: 'The version compared from'
    value: ${{ steps.analyze.outputs.current_version }}
  next_version:
    description: 'Calculated next semantic version'
    value: ${{ steps.analyze.outputs.next_version }}
  changelogs:
    description: 'JSON object with changelogs: {audience: {language: markdown}}. Default: {default: {en: "..."}}. See README for schema.'
    value: ${{ steps.analyze.outputs.changelogs }}
  metadata:
    description: 'JSON object with release metadata per audience and language: {audience: {language: {title, summary, highlights}}}'
    value: ${{ steps.analyze.outputs.metadata }}
  changes:
    description: 'JSON array of structured changes from Phase 1 analysis'
    value: ${{ steps.analyze.outputs.changes }}
  stats:
    description: 'JSON object with change statistics: {features, fixes, breaking, contributors, ...}'
    value: ${{ steps.analyze.outputs.stats }}
  breaking_changes:
    description: 'JSON array of detected breaking changes'
    value: ${{ steps.analyze.outputs.breaking_changes }}
  reasoning:
    description: 'LLM reasoning for the version suggestion'
    value: ${{ steps.analyze.outputs.reasoning }}
  usage:
    description: 'JSON object with LLM usage statistics: {total_calls, total_tokens, total_latency_ms, phase1_tokens, phase2_tokens, ...}'
    value: ${{ steps.analyze.outputs.usage }}
  warnings:
    description: 'JSON array of warning messages (staleness, truncation, etc.)'
    value: ${{ steps.analyze.outputs.warnings }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/src/requirements.txt

    - name: Run analysis
      id: analyze
      shell: bash
      env:
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_MODEL_ANALYSIS: ${{ inputs.model_analysis }}
        INPUT_MODEL_CHANGELOG: ${{ inputs.model_changelog }}
        INPUT_CURRENT_VERSION: ${{ inputs.current_version }}
        INPUT_HEAD_REF: ${{ inputs.head_ref }}
        INPUT_INCLUDE_DIFFS: ${{ inputs.include_diffs }}
        INPUT_MAX_COMMITS: ${{ inputs.max_commits }}
        INPUT_TEMPERATURE: ${{ inputs.temperature }}
        INPUT_MAX_TOKENS: ${{ inputs.max_tokens }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_CONTENT_OVERRIDE: ${{ inputs.content_override }}
        INPUT_CHANGELOG_CONFIG: ${{ inputs.changelog_config }}
        INPUT_VALIDATE_INJECTIONS: ${{ inputs.validate_injections }}
        INPUT_VALIDATION_MODEL: ${{ inputs.validation_model }}
        INPUT_CONTEXT_FILES: ${{ inputs.context_files }}
        INPUT_CONTEXT_MAX_TOKENS: ${{ inputs.context_max_tokens }}
        INPUT_ANALYZE_DIFFS: ${{ inputs.analyze_diffs }}
        INPUT_DIFF_EXCLUDE_PATTERNS: ${{ inputs.diff_exclude_patterns }}
        INPUT_DIFF_MAX_FILES: ${{ inputs.diff_max_files }}
        INPUT_DIFF_MAX_TOTAL_LINES: ${{ inputs.diff_max_total_lines }}
      run: |
        python ${{ github.action_path }}/src/analyze.py
