# Basic release workflow using llm-semver-action
# Save this as .github/workflows/release.yml

name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full git history

      - uses: nosovj/llm-semver-action@v1
        id: semver
        with:
          model: anthropic/claude-3-haiku-20240307
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.next_version }}
          name: ${{ steps.semver.outputs.next_version }}
          body: ${{ steps.semver.outputs.changelog }}
          draft: false
          prerelease: false
