# Basic release workflow using llm-release-action
# Save this as .github/workflows/release.yml

name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full git history

      - uses: nosovj/llm-release-action@v1
        id: release
        with:
          model: bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Create GitHub Release
        run: |
          CHANGELOG=$(echo '${{ steps.release.outputs.changelogs }}' | jq -r '.default.en')
          gh release create ${{ steps.release.outputs.next_version }} \
            --title "${{ steps.release.outputs.next_version }}" \
            --notes "$CHANGELOG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
