# PR workflow that comments the suggested version
# Save this as .github/workflows/pr-version.yml

name: PR Version Check
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nosovj/llm-semver-action@v1
        id: semver
        with:
          model: anthropic/claude-3-haiku-20240307
          dry_run: true
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const bump = '${{ steps.semver.outputs.bump }}';
            const currentVersion = '${{ steps.semver.outputs.current_version }}';
            const nextVersion = '${{ steps.semver.outputs.next_version }}';
            const reasoning = `${{ steps.semver.outputs.reasoning }}`;

            const body = `## Version Analysis

            | Current | Bump | Next |
            |---------|------|------|
            | ${currentVersion} | **${bump}** | ${nextVersion} |

            ### Reasoning
            ${reasoning}
            `;

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existingComment = comments.find(c =>
              c.user.type === 'Bot' && c.body.includes('## Version Analysis')
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body,
              });
            }
